version: '3.7'

services:
  appServer:
    image: apptests:latest
    container_name: 'appserver'
    ports:
      - '5500:8080'

  appFront:
    image: frontapp:latest
    container_name: 'frontapp'
    ports:
      - '3000:3000'